language: python

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=uno
- BOARD=leonardo
- BOARD=micro
- BOARD=megaatmega2560
- BOARD=yun

script:
- for e in $(find examples -name \*.ino); do
    platformio ci --board=$BOARD --lib=. $e;
  done
